services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    environment:
      - DEBUG_DB=${DEBUG_DB}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - db
    volumes:
    - .:/app:delegated
    - /app/node_modules
    command: sh -c "npm install --include=dev && npm run dev"

volumes:
  postgres_data:
